[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "funcsv2db"
version = "0.0.1"
description = "A CSV processor to insert to database for use in Funcwords project."
license = "MIT"

[tool.hatch.build.targets.wheel]
only-include = ["funcsv2db.py"]
